version: "3.8"
services:
    db: 
        image: mongo      
        volumes:
        - /c/Users/Joshua/Documents/mongodb_bind_mount/:/data/db
        ports:
        - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/covidCheckerDb --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 20s
        restart: unless-stopped
    covidchecker: 
        image: covidchecker
        ports:
        - 8080:8080
        depends_on:
            db: 
                condition: service_healthy