version: "3.8"
services:
    mongodb: 
        image: mongo
        container_name: mongodb
        volumes:
        - /home/ubuntu/deployment-files/covidchecker/mongo_data/:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/covidCheckerDb --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 20s
        restart: unless-stopped
    covidchecker: 
        image: covidchecker
        container_name: covidchecker_microservice
        depends_on:
            mongodb: 
                condition: service_healthy
    covidchecker_frontend:
        image: covidcheckerfrontend
        container_name: covidchecker_frontend
        depends_on:
            - covidchecker
        ports:
        - 80:80
