version: "3.8"
services:
    mongodb: 
        image: mongo
        container_name: mongodb
        volumes:
        - /home/ubuntu/deployment-files/transaction-reconciliator/mongo_data/:/data/db
        ports:
        - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/transactionReconciliatorDb --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 20s
        restart: unless-stopped
    transaction-reconciliator: 
        image: transaction-reconciliator
        container_name: transaction-reconciliator_microservice
        ports:
        - 8080:8080
        depends_on:
            mongodb: 
                condition: service_healthy
