version: "2.1"
services:
    mysql: 
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'my-secret-pw'
        volumes:
        - /home/ubuntu/deployment-files/transaction-reconciliator/mysql_data/:/var/lib/mysql
        ports:
        - 3306:3306
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    transaction-reconciliator: 
        image: transaction-reconciliator
        container_name: transaction-reconciliator_microservice
        ports:
        - 8080:8080
        restart: unless-stopped  
        depends_on:
            mysql: 
                condition: service_healthy
    transaction-reconciliator-frontend:
        image: transaction-reconciliator-frontend
        container_name: transaction-reconciliator-frontend
        ports: 
        - 3000:3000
        restart: unless-stopped
