version: "3.8"
services:
    mysql: 
        image: mysql
        container_name: mysql
        volumes:
        - /home/ubuntu/deployment-files/transaction-reconciliator/mysql_data/:/var/lib/mysql
        ports:
        - 3306:3306
        restart: unless-stopped
    transaction-reconciliator: 
        image: transaction-reconciliator
        container_name: transaction-reconciliator_microservice
        ports:
        - 8080:8080
        depends_on:
            mysql: 
                condition: service_healthy
